[project]
name = "classera-agentic-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "n3gm", email = "lamaalharbi273@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
classera-agentic-workflow = "classera_agentic_workflow:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
